name: health CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on:  windows-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Java 17
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'

      # Step 3: Build with Maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Step 4: Run tests
      - name: Run tests
        run: mvn test
